[build-system]
requires = ["setuptools==83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ada-ui-component-global-indicator"
version = "0.2.0"
description = "Indicador global reutilizable para herramientas ADA"
requires-python = "==3.14.2"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "ada-ui-framework-core==0.1.0",
    "atlanticus-web==0.1.0",
    "dash==4.4.1",
]

[tool.uv.sources]
ada-ui-framework-core = { workspace = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
include = ["ada.ui.components.global_indicator*"]

[tool.setuptools.package-data]
"ada.ui.components.global_indicator" = [
    "py.typed",
    "resources/css/*.css",
    "resources/css/css.list",
]
