# Espejo pedagógico: Operaciones Integradas declara nueve componentes reales; Gestión Carguío Turno es una sola card compartida entre Carguío y Transporte.
from ..enums import ToolScope, ToolSectionKind, ToolSourceKey, ToolTarget
from ..models import ToolManifest, ToolSection, ToolSource

_KPI = frozenset({ToolTarget.KPI})
_ALARM = frozenset({ToolTarget.ALARM})
_KPI_ALARM = frozenset({ToolTarget.KPI, ToolTarget.ALARM})


def _alarm_subcomponent(
    *,
    component: str,
    subcomponent: str,
    display_name: str,
    scope: ToolScope,
    linked_component_keys: tuple[str, ...] = (),
) -> ToolSection:
    return ToolSection(
        component=component,
        subcomponent=subcomponent,
        display_name=display_name,
        kind=ToolSectionKind.SUBCOMPONENT,
        scope=scope,
        targets=_ALARM,
        linked_component_keys=linked_component_keys,
    )


INTEGRATED_OPERATIONS_MANIFEST = ToolManifest(
    tool_key='integrated_operations',
    display_name='Operaciones Integradas',
    sources=(
        ToolSource(ToolSourceKey.PI, stale_after_seconds=300),
        ToolSource(ToolSourceKey.DISPATCH, stale_after_seconds=600),
    ),
    sections=(
        ToolSection(
            key='header',
            display_name='Header',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.GLOBAL,
        ),
        ToolSection(
            key='global_indicators',
            display_name='Indicadores Globales',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            parent_key='header',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            component='global_indicators',
            subcomponent='mine',
            display_name='Indicadores Globales Mina',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.MINE,
            targets=_KPI,
        ),
        ToolSection(
            component='global_indicators',
            subcomponent='plant',
            display_name='Indicadores Globales Planta',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.PLANT,
            targets=_KPI,
        ),
        ToolSection(
            key='alarm_management',
            display_name='Gestión de Alarmas',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            component='alarm_management',
            subcomponent='mine',
            display_name='Gestión de Alarmas Mina',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.MINE,
        ),
        ToolSection(
            component='alarm_management',
            subcomponent='plant',
            display_name='Gestión de Alarmas Planta',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.PLANT,
        ),
        ToolSection(
            key='alarm_status',
            display_name='Estado de Alarmas',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            key='time_status',
            display_name='Estado Temporal',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='body',
            display_name='Contenido',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.GLOBAL,
        ),
        ToolSection(
            key='mine',
            display_name='Mina',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.MINE,
            parent_key='body',
        ),
        ToolSection(
            key='general_mina',
            display_name='General Mina',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='general_mina',
            subcomponent='movimiento_mina',
            display_name='Movimiento Mina',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='general_mina',
            subcomponent='remanentes',
            display_name='Remanentes',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='general_mina',
            subcomponent='perforacion',
            display_name='Perforación',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='general_mina',
            subcomponent='mp10',
            display_name='MP10',
            scope=ToolScope.MINE,
        ),
        ToolSection(
            key='carguio',
            display_name='Carguío',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='carguio',
            subcomponent='equipos_servicio',
            display_name='Equipos de Servicio',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='carguio',
            subcomponent='mezcla_hacia_chancado',
            display_name='Mezcla hacia Chancado',
            scope=ToolScope.MINE,
        ),
        ToolSection(
            key='transporte',
            display_name='Transporte',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='transporte',
            subcomponent='transporte_global',
            display_name='Transporte Global • Turno',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='transporte',
            subcomponent='numero_operativos',
            display_name='N° Operativos • Turno',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='transporte',
            subcomponent='tiempos_y_colas',
            display_name='Tiempos y Colas • Turno',
            scope=ToolScope.MINE,
        ),
        _alarm_subcomponent(
            component='carguio',
            subcomponent='gestion_carguio_turno',
            display_name='Gestión Carguío • Turno',
            scope=ToolScope.MINE,
            linked_component_keys=('transporte',),
        ),
        ToolSection(
            key='chancado_stmg',
            display_name='Chancado-STMG',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='chancado_stmg',
            subcomponent='chancado_stmg',
            display_name='Chancado-STMG',
            scope=ToolScope.MINE,
        ),
        ToolSection(
            key='plant',
            display_name='Planta',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.PLANT,
            parent_key='body',
        ),
        ToolSection(
            key='stockpile_chacay',
            display_name='Stockpile - Chacay',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='stockpile_chacay',
            subcomponent='stockpile_chacay',
            display_name='Stockpile Chacay',
            scope=ToolScope.PLANT,
        ),
        _alarm_subcomponent(
            component='stockpile_chacay',
            subcomponent='tendencia_alimentado',
            display_name='Tendencia Alimentado',
            scope=ToolScope.PLANT,
        ),
        ToolSection(
            key='molienda',
            display_name='Molienda',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='molienda',
            subcomponent='molienda',
            display_name='Molienda',
            scope=ToolScope.PLANT,
        ),
        ToolSection(
            key='flotacion',
            display_name='Flotación',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='flotacion',
            subcomponent='colectiva',
            display_name='Colectiva',
            scope=ToolScope.PLANT,
        ),
        _alarm_subcomponent(
            component='flotacion',
            subcomponent='selectiva',
            display_name='Selectiva',
            scope=ToolScope.PLANT,
        ),
        ToolSection(
            key='transporte_fluidos',
            display_name='Transporte de Fluidos',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='transporte_fluidos',
            subcomponent='str',
            display_name='STR',
            scope=ToolScope.PLANT,
        ),
        _alarm_subcomponent(
            component='transporte_fluidos',
            subcomponent='stc',
            display_name='STC',
            scope=ToolScope.PLANT,
        ),
        _alarm_subcomponent(
            component='transporte_fluidos',
            subcomponent='tranque',
            display_name='Tranque',
            scope=ToolScope.PLANT,
        ),
        _alarm_subcomponent(
            component='transporte_fluidos',
            subcomponent='sta',
            display_name='STA',
            scope=ToolScope.PLANT,
        ),
        ToolSection(
            key='puerto',
            display_name='Puerto',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        _alarm_subcomponent(
            component='puerto',
            subcomponent='puerto',
            display_name='Puerto',
            scope=ToolScope.PLANT,
        ),
        _alarm_subcomponent(
            component='puerto',
            subcomponent='desaladora',
            display_name='Desaladora',
            scope=ToolScope.PLANT,
        ),
    ),
)
