from ..enums import ToolScope, ToolSectionKind, ToolSourceKey, ToolTarget
from ..models import ToolManifest, ToolSection, ToolSource

_KPI = frozenset({ToolTarget.KPI})
_ALARM = frozenset({ToolTarget.ALARM})
_KPI_ALARM = frozenset({ToolTarget.KPI, ToolTarget.ALARM})

# Manifest estático de IO: identifica unidades configurables sin definir cómo se obtienen o renderizan los datos.
INTEGRATED_OPERATIONS_MANIFEST = ToolManifest(
    tool_key='integrated_operations',
    display_name='Operaciones Integradas',
    sources=(
        ToolSource(ToolSourceKey.PI, stale_after_seconds=300),
        ToolSource(ToolSourceKey.DISPATCH, stale_after_seconds=600),
    ),
    sections=(
        ToolSection(
            key='header',
            display_name='Header',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.GLOBAL,
        ),
        ToolSection(
            key='global_indicators',
            display_name='Indicadores Globales',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            parent_key='header',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            component='global_indicators',
            subcomponent='mine',
            display_name='Indicadores Globales Mina',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.MINE,
            targets=_KPI,
        ),
        ToolSection(
            component='global_indicators',
            subcomponent='plant',
            display_name='Indicadores Globales Planta',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.PLANT,
            targets=_KPI,
        ),
        ToolSection(
            key='alarm_management',
            display_name='Gestión de Alarmas',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            component='alarm_management',
            subcomponent='mine',
            display_name='Gestión de Alarmas Mina',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.MINE,
        ),
        ToolSection(
            component='alarm_management',
            subcomponent='plant',
            display_name='Gestión de Alarmas Planta',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.PLANT,
        ),
        ToolSection(
            key='alarm_status',
            display_name='Estado de Alarmas',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            key='time_status',
            display_name='Estado Temporal',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.GLOBAL,
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='body',
            display_name='Contenido',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.GLOBAL,
        ),
        ToolSection(
            key='mine',
            display_name='Mina',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.MINE,
            parent_key='body',
        ),
        ToolSection(
            key='general_mina',
            display_name='General Mina',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='carguio',
            display_name='Carguío',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='transporte',
            display_name='Transporte',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        # Caso especial compartido: mantiene identidad propia y declara su vínculo con ambos componentes.
        ToolSection(
            key='carguio_transporte',
            display_name='Carguío y Transporte',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
            linked_component_keys=('carguio', 'transporte'),
        ),
        ToolSection(
            key='chancado_stmg',
            display_name='Chancado-STMG',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='plant',
            display_name='Planta',
            kind=ToolSectionKind.REGION,
            scope=ToolScope.PLANT,
            parent_key='body',
        ),
        ToolSection(
            key='stock_chacay',
            display_name='Stock Chacay',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='molienda',
            display_name='Molienda',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='flotacion',
            display_name='Flotación',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        # Las cards conocidas se declaran con identidad local; ToolSection deriva la key final.
        ToolSection(
            component='flotacion',
            subcomponent='colectiva',
            display_name='Flotación Colectiva',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.PLANT,
            targets=_ALARM,
        ),
        ToolSection(
            component='flotacion',
            subcomponent='selectiva',
            display_name='Flotación Selectiva',
            kind=ToolSectionKind.SUBCOMPONENT,
            scope=ToolScope.PLANT,
            targets=_ALARM,
        ),
        ToolSection(
            key='transporte_fluidos',
            display_name='Transporte de Fluidos',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            key='puerto',
            display_name='Puerto',
            kind=ToolSectionKind.COMPONENT,
            scope=ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
    ),
)
