from ..enums import ToolScope, ToolSectionKind, ToolSourceKey, ToolTarget
from ..models import ToolManifest, ToolSection, ToolSource

_KPI = frozenset({ToolTarget.KPI})
_KPI_ALARM = frozenset({ToolTarget.KPI, ToolTarget.ALARM})

# Configuración de referencia: PI 5 minutos y Dispatch 10 minutos.
INTEGRATED_OPERATIONS_MANIFEST = ToolManifest(
    tool_key='integrated_operations',
    display_name='Operaciones Integradas',
    sources=(
        ToolSource(ToolSourceKey.PI, stale_after_seconds=300),
        ToolSource(ToolSourceKey.DISPATCH, stale_after_seconds=600),
    ),
    sections=(
        ToolSection('header', 'Header', ToolSectionKind.REGION, ToolScope.GLOBAL),
        ToolSection(
            'global_indicators',
            'Indicadores Globales',
            ToolSectionKind.COMPONENT,
            ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            'global_indicators_mine',
            'Indicadores Globales Mina',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.MINE,
            parent_key='global_indicators',
            targets=_KPI,
        ),
        ToolSection(
            'global_indicators_plant',
            'Indicadores Globales Planta',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.PLANT,
            parent_key='global_indicators',
            targets=_KPI,
        ),
        ToolSection(
            'alarm_management',
            'Gestión de Alarmas',
            ToolSectionKind.COMPONENT,
            ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            'alarm_management_mine',
            'Gestión de Alarmas Mina',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.MINE,
            parent_key='alarm_management',
        ),
        ToolSection(
            'alarm_management_plant',
            'Gestión de Alarmas Planta',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.PLANT,
            parent_key='alarm_management',
        ),
        ToolSection(
            'alarm_status',
            'Estado de Alarmas',
            ToolSectionKind.COMPONENT,
            ToolScope.GLOBAL,
            parent_key='header',
        ),
        ToolSection(
            'time_status',
            'Estado Temporal',
            ToolSectionKind.COMPONENT,
            ToolScope.GLOBAL,
        ),
        ToolSection('body', 'Contenido', ToolSectionKind.REGION, ToolScope.GLOBAL),
        ToolSection(
            'mine',
            'Mina',
            ToolSectionKind.REGION,
            ToolScope.MINE,
            parent_key='body',
        ),
        ToolSection(
            'general_mina',
            'General Mina',
            ToolSectionKind.COMPONENT,
            ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'carguio_transporte',
            'Carguío y Transporte',
            ToolSectionKind.COMPONENT,
            ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'carguio',
            'Carguío',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.MINE,
            parent_key='carguio_transporte',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'transporte',
            'Transporte',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.MINE,
            parent_key='carguio_transporte',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'chancado_stmg',
            'Chancado-STMG',
            ToolSectionKind.COMPONENT,
            ToolScope.MINE,
            parent_key='mine',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'plant',
            'Planta',
            ToolSectionKind.REGION,
            ToolScope.PLANT,
            parent_key='body',
        ),
        ToolSection(
            'stock_chacay',
            'Stock Chacay',
            ToolSectionKind.COMPONENT,
            ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'molienda',
            'Molienda',
            ToolSectionKind.COMPONENT,
            ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'flotacion',
            'Flotación',
            ToolSectionKind.COMPONENT,
            ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'flotacion_colectiva',
            'Flotación Colectiva',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.PLANT,
            parent_key='flotacion',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'flotacion_selectiva',
            'Flotación Selectiva',
            ToolSectionKind.SUBCOMPONENT,
            ToolScope.PLANT,
            parent_key='flotacion',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'transporte_fluidos',
            'Transporte de Fluidos',
            ToolSectionKind.COMPONENT,
            ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
        ToolSection(
            'puerto',
            'Puerto',
            ToolSectionKind.COMPONENT,
            ToolScope.PLANT,
            parent_key='plant',
            targets=_KPI_ALARM,
        ),
    ),
)
