[build-system]
requires = ["setuptools==83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atlanticus-web-reference"
version = "0.1.0"
requires-python = "==3.14.2"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "atlanticus-web==0.1.0",
    "atlanticus-web-navigation==0.1.0",
    "atlanticus-web-composition-navigation-activity==0.1.0",
    "atlanticus-web-composition-users-navigation==0.1.0",
    "atlanticus-web-identity-local==0.1.0",
    "atlanticus-web-identity-app-service==0.1.0",
    "atlanticus-web-users-local==0.1.0",
    "atlanticus-web-users-activity==0.1.0",
    "gunicorn==26.0.0",
]

[tool.uv.sources]
atlanticus-web = { workspace = true }
atlanticus-web-navigation = { workspace = true }
atlanticus-web-composition-navigation-activity = { workspace = true }
atlanticus-web-composition-users-navigation = { workspace = true }
atlanticus-web-identity-local = { workspace = true }
atlanticus-web-identity-app-service = { workspace = true }
atlanticus-web-users-local = { workspace = true }
atlanticus-web-users-activity = { workspace = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["atlanticus_web_reference*"]

[tool.setuptools.package-data]
"atlanticus_web_reference" = [
    "resources/css/*.css",
    "resources/css/css.list",
    "resources/js/*.js",
    "resources/js/js.list",
]
