[build-system]
requires = ["setuptools==83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ada-application-configuration-manager"
version = "0.2.22"
requires-python = "==3.14.2"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "ada-composition-configuration-manager==0.1.22",
    "ada-configuration-kpis[web]==0.2.4",
    "ada-configuration-tools[web]==0.1.9",
    "ada-contracts-tool-manifest==0.1.0",
    "ada-ui-framework-core==0.1.0",
    "ada-ui-shell-navigation==0.1.0",
    "atlanticus-web==0.1.0",
    "atlanticus-web-manager==0.3.11",
    "atlanticus-web-navigation==0.1.0",
    "atlanticus-web-navigation-configuration[web]==0.1.5",
    "atlanticus-web-users-configuration[web]==0.1.6",
    "gunicorn==26.0.0",
]

[project.scripts]
ada-configuration-manager-preview = "ada.applications.configuration_manager.__main__:main"

[tool.uv.sources]
ada-composition-configuration-manager = { workspace = true }
ada-configuration-kpis = { workspace = true }
ada-configuration-tools = { workspace = true }
ada-contracts-tool-manifest = { workspace = true }
ada-ui-framework-core = { workspace = true }
ada-ui-shell-navigation = { workspace = true }
atlanticus-web = { path = "../../../../web/framework/core", editable = true }
atlanticus-web-manager = { path = "../../../../web/capabilities/manager", editable = true }
atlanticus-web-navigation = { path = "../../../../web/capabilities/navigation/core", editable = true }
atlanticus-web-navigation-configuration = { path = "../../../../web/capabilities/navigation/configuration", editable = true }
atlanticus-web-users-configuration = { path = "../../../../web/capabilities/users/configuration", editable = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["ada.applications.configuration_manager*"]

[tool.setuptools.package-data]
"ada.applications.configuration_manager" = [
    "py.typed",
    "resources/img/*.png",
    "resources/img/*.svg",
]
