[build-system]
requires = ["setuptools==83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atlanticus-web-manager"
version = "0.3.4"
description = "Capability administrativa modular para aplicaciones Atlanticus Web"
requires-python = "==3.14.2"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "atlanticus-web==0.1.0",
    "dash==4.4.1",
]

[tool.uv.sources]
atlanticus-web = { workspace = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
include = ["atlanticus.web.manager*"]

[tool.setuptools.package-data]
"atlanticus.web.manager" = [
    "py.typed",
    "resources/css/*.css",
    "resources/css/css.list",
]
